### ISSUE TITLE
Unable to arm/disarm when scan interval is used

### ISSUE THREAD

**Issue by palazzem** [palazzem/ha-econnect-alarm#117]
**Describe the bug**
When "Scan Interval" is set to a certain value (user reported `120`s), the integration doesn't have a valid access token anymore, resulting in a 401 error.

**Error message**
```
Logger: custom_components.econnect_metronet.devices
Source: custom_components/econnect_metronet/devices.py:284
Integration: e-Connect/Metronet Alarm (documentation, issues)
First occurred: 18:16:42 (1 occurrences)
Last logged: 18:16:42

Device | Error while arming the system: "User not authenticated"
Errore 2:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/econnect_metronet/devices.py:280
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:16:42 (1 occurrences)
Last logged: 18:16:42

[547777283008] 401 Client Error: Unauthorized for url: https://connect.elmospa.com/api/panel/syncLogin
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
File "/config/custom_components/econnect_metronet/decorators.py", line 26, in func_wrapper
  File "/config/custom_components/econnect_metronet/alarm_control_panel.py", line 121, in async_alarm_arm_night
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/econnect_metronet/devices.py", line 285, in arm
  File "/config/custom_components/econnect_metronet/devices.py", line 280, in arm
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in enter
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elmo/api/client.py", line 179, in lock
    raise err
  File "/usr/local/lib/python3.11/site-packages/elmo/api/client.py", line 173, in lock
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://connect.elmospa.com/api/panel/syncLogin
```

**Expected behavior**
Even if the access token is expired, it should be renewed so that the API call results in a proper 401 if and only if the actual authentication is not correct.

**Additional context**
This happens only if scan interval is set to a reasonable long period.

**To Reproduce**
- Set scan interval to 120
- Wait for the access token to expire
- Launch an arm command before the scan interval refreshes the token

**Environment**
 - Operating System (OS): n/a
 - Library version (commit or version number): 2.2.1
 - Home Assistant version: n/a
 - Last working Home Assistant release (if known): n/a

**Comment by palazzem** [comment]
Putting this on-hold as we wait for user's feedback.

**Comment by andr3a88** [comment]
I think I encountered the same problem:

To Reproduce

+ Set scan interval to 3600
+ Launch an arm command from homekit
+ The alarm stay in an `arming` probably up to the next refresh

![IMG_0237](https://github.com/palazzem/ha-econnect-alarm/assets/6755254/b0420370-975f-4829-b911-aef8c344229e)

Logs:
````
2024-03-08 20:30:57.196 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall alarm_control_panel.alarm_arm_home
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/elmo/api/client.py", line 183, in lock
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://metronet.iessonline.com/api/panel/syncLogin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2335, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/econnect_metronet/decorators.py", line 27, in func_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/econnect_metronet/alarm_control_panel.py", line 110, in async_alarm_arm_home
    await self.hass.async_add_executor_job(self._device.arm, code, self._device._sectors_home)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/econnect_metronet/devices.py", line 348, in arm
    with self._connection.lock(code, user_id=user_id):
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/elmo/api/client.py", line 190, in lock
    raise InvalidToken
elmo.api.exceptions.InvalidToken: Used token is not valid. You must authenticate again.
````
