### ISSUE TITLE
Missing alarm panel states

### ISSUE THREAD

**Issue by palazzem** [palazzem/ha-econnect-alarm#29]
### Overview

Import from https://github.com/palazzem/econnect-python/issues/103

--

**Stati non presenti: arm_custom_bypass, arm_vacation e arm_home **

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:851
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:48:27 (1 occurrences)
Last logged: 20:48:27

[548367750464] Entity alarm_control_panel.alarm_panel does not support this service.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.alarm_panel does not support this service.

STATO SENSORI acceso/spento:
Inizialmente avevo inteso che i sensori fossero accessi/spenti quando inclusi o esclusi. in realtà, In caso di sensori volumetrici sono sempre spenti. Si accendono solo quando scattano. Quindi lo stato potrebbe portare a fraintendimenti tra acceso/spento e inclusi/esclusi

**Comment by palazzem** [comment]
To complete this issue, many states are not supported and so such errors happen when users want to use one of these. All states that must be supported are documented here: https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#supported-features
